scaffold_policy_name="hello_habichef"
pkg_name=hello_habichef
pkg_origin=cuddletech
pkg_version="0.0.1"
pkg_maintainer="@benr"
pkg_license=("Apache-2.0")
pkg_description="HabiChef Hello World"
pkg_upstream_url="http://chef.io"
pkg_scaffolding="core/scaffolding-chef"
